"""revenue engine

Revision ID: 2eecfa6c8c19
Revises: 7f0f6bab7b3b
Create Date: 2026-07-17 23:44:30.124544

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2eecfa6c8c19'
down_revision: Union[str, None] = '7f0f6bab7b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('trigger_type', sa.String(), nullable=True),
    sa.Column('trigger_event', sa.String(), nullable=True),
    sa.Column('delay_minutes', sa.Integer(), nullable=True),
    sa.Column('condition', sa.JSON(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('message_template', sa.Text(), nullable=True),
    sa.Column('cancel_on_events', sa.JSON(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('automation_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_automation_rules_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_automation_rules_id'), ['id'], unique=False)

    op.create_table('domain_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domain_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_events_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_events_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_events_processed'), ['processed'], unique=False)

    op.create_table('scheduled_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('rule_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['automation_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_actions_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_actions_due_at'), ['due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_actions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_actions_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_actions_status'), ['status'], unique=False)

    op.create_table('service_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('service_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_service_packages_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_service_packages_id'), ['id'], unique=False)

    op.create_table('waitlist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=True),
    sa.Column('preferred_date', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('notified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_leads.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('waitlist_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_waitlist_entries_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_waitlist_entries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_waitlist_entries_status'), ['status'], unique=False)

    op.create_table('patient_packages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('sessions_total', sa.Integer(), nullable=False),
    sa.Column('sessions_used', sa.Integer(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('purchased_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['package_id'], ['service_packages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_packages_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_packages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_packages_patient_id'), ['patient_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('provider_ref', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_leads.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)

    op.create_table('revenue_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('patient_package_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_leads.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['patient_package_id'], ['patient_packages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revenue_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revenue_records_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revenue_records_id'), ['id'], unique=False)

    op.create_table('review_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['patient_leads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_requests_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_requests_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_requests_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_requests_status'), ['status'], unique=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_source', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('conversation_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_appointments_conversation_id', 'conversations', ['conversation_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('monthly_fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('deposit_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('google_review_url', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('digest_enabled', sa.Boolean(), nullable=True))

    with op.batch_alter_table('patient_leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referral_code', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('referred_by_patient_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_patient_leads_referral_code'), ['referral_code'], unique=False)
        batch_op.create_foreign_key('fk_patient_leads_referred_by', 'patient_leads', ['referred_by_patient_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_doctor_id', 'doctors', ['doctor_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        pass  # named FKs dropped with batch table rebuild
        batch_op.drop_column('doctor_id')

    with op.batch_alter_table('patient_leads', schema=None) as batch_op:
        pass  # named FKs dropped with batch table rebuild
        batch_op.drop_index(batch_op.f('ix_patient_leads_referral_code'))
        batch_op.drop_column('referred_by_patient_id')
        batch_op.drop_column('referral_code')

    with op.batch_alter_table('clinics', schema=None) as batch_op:
        batch_op.drop_column('digest_enabled')
        batch_op.drop_column('google_review_url')
        batch_op.drop_column('deposit_amount')
        batch_op.drop_column('monthly_fee')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        pass  # named FKs dropped with batch table rebuild
        batch_op.drop_column('conversation_id')
        batch_op.drop_column('booking_source')

    with op.batch_alter_table('review_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_requests_status'))
        batch_op.drop_index(batch_op.f('ix_review_requests_patient_id'))
        batch_op.drop_index(batch_op.f('ix_review_requests_id'))
        batch_op.drop_index(batch_op.f('ix_review_requests_clinic_id'))

    op.drop_table('review_requests')
    with op.batch_alter_table('revenue_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revenue_records_id'))
        batch_op.drop_index(batch_op.f('ix_revenue_records_clinic_id'))

    op.drop_table('revenue_records')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_id'))
        batch_op.drop_index(batch_op.f('ix_payments_clinic_id'))

    op.drop_table('payments')
    with op.batch_alter_table('patient_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_packages_patient_id'))
        batch_op.drop_index(batch_op.f('ix_patient_packages_id'))
        batch_op.drop_index(batch_op.f('ix_patient_packages_clinic_id'))

    op.drop_table('patient_packages')
    with op.batch_alter_table('waitlist_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_waitlist_entries_status'))
        batch_op.drop_index(batch_op.f('ix_waitlist_entries_id'))
        batch_op.drop_index(batch_op.f('ix_waitlist_entries_clinic_id'))

    op.drop_table('waitlist_entries')
    with op.batch_alter_table('service_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_service_packages_id'))
        batch_op.drop_index(batch_op.f('ix_service_packages_clinic_id'))

    op.drop_table('service_packages')
    with op.batch_alter_table('scheduled_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_actions_status'))
        batch_op.drop_index(batch_op.f('ix_scheduled_actions_patient_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_actions_id'))
        batch_op.drop_index(batch_op.f('ix_scheduled_actions_due_at'))
        batch_op.drop_index(batch_op.f('ix_scheduled_actions_clinic_id'))

    op.drop_table('scheduled_actions')
    with op.batch_alter_table('domain_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_events_processed'))
        batch_op.drop_index(batch_op.f('ix_domain_events_patient_id'))
        batch_op.drop_index(batch_op.f('ix_domain_events_id'))
        batch_op.drop_index(batch_op.f('ix_domain_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_domain_events_clinic_id'))

    op.drop_table('domain_events')
    with op.batch_alter_table('automation_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_automation_rules_id'))
        batch_op.drop_index(batch_op.f('ix_automation_rules_clinic_id'))

    op.drop_table('automation_rules')
    # ### end Alembic commands ###
